name: Bug Report
description: Creat a bug report in fitting console backend.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What bug brings you here?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: what-expected
    attributes:
      label: What did you expect to happen?
      description: What should its normal behavior be?
      placeholder: Tell us what you expected!
    validations:
      required: true
  - type: textarea
    id: how-reproduce
    attributes:
      label: How can we reproduce it (as minimally and precisely as possible)?
      placeholder: Tell us how to reproduce this bug!
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Anything else we need to know?
  - type: textarea
    id: branch
    attributes:
      label: |
        On which branch did you encounter this problem?
        Use `git rev-parse --abbrev-ref HEAD` to get branch name and paste below.
      placeholder: |
        e.g. dev-remote_unboxing
    validations:
      required: true
